### ISSUE TITLE
Install.py - SyntaxError: Non-ASCII character '\xc3'

### ISSUE THREAD

**Issue by kobi80** [roe-dl/weewx-GTS#1]
Wenn ich die Erweiterung installieren möchte kommt folgende Fehlermeldung: 

sudo wee_extension --install weewx-GTS.zip
Request to install 'weewx-GTS.zip'
Extracting from zip archive weewx-GTS.zip
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 125, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 147, in install_from_dir
    extension_dir)
  File "/usr/share/weewx/weecfg/__init__.py", line 1866, in get_extension_instal                                                                                        ler
    __import__('install')
  File "/var/tmp/weewx-GTS-master/install.py", line 15
SyntaxError: Non-ASCII character '\xc3' in file /var/tmp/weewx-GTS-master/instal                                                                                        l.py on line 15, but no encoding declared; see http://python.org/dev/peps/pep-02                                                                                        63/ for details

**Comment by roe-dl** [comment]
Der scheint ein Problem mit dem Umlaut zu haben. Ich habe ihn durch 'ue' ersetzt. Bitte nochmal probieren.

**Comment by kobi80** [comment]
Hi
Danke für die Hilfe, aber geht leider immer noch nicht.
wie kann ich die Erweiterung manuell einbinden ?
##################################
nas@nas:/usr/share/weewx/user$ sudo wee_extension --install weewx-GTS.zip
Request to install 'weewx-GTS.zip'
Extracting from zip archive weewx-GTS.zip
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 125, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 147, in install_from_dir
    extension_dir)
  File "/usr/share/weewx/weecfg/__init__.py", line 1866, in get_extension_installer
    __import__('install')
  File "/var/tmp/weewx-GTS-master/install.py", line 20
    files=[('bin/user', ['bin/user/GTS.py'])]
        ^
SyntaxError: invalid syntax

**Comment by cnbr** [comment]
Habe es gerade auch mal installiert, hinter dem config in der install.py muss noch ein Komma, dann läuft es durch
 `config={},`

Umlaute gehen, die install.py ist nur als UTF-8 Unicode gespeichert, da muss in der Shell auch UTF8 eingestellt sein. 
`LANG=de_DE.UTF-8`

**Comment by kobi80** [comment]
nachdem ich auch das Komma nachträglich gesetzt habe, ist auch das Install script durchgelaufen.
Nächste Problem, gleicher Fehler in der GTS.py

nas@nas:/tmp$ **sudo wee_reports**
Using configuration file /etc/weewx/weewx.conf
Traceback (most recent call last):
  File "/usr/share/weewx/wee_reports", line 103, in <module>
    main()
  File "/usr/share/weewx/wee_reports", line 69, in main
    engine = weewx.engine.DummyEngine(config_dict)
  File "/usr/share/weewx/weewx/engine.py", line 93, in __init__
    self.loadServices(config_dict)
  File "/usr/share/weewx/weewx/engine.py", line 161, in loadServices
    obj = weeutil.weeutil.get_object(svc)(self, config_dict)
  File "/usr/share/weewx/weeutil/weeutil.py", line 1093, in get_object
    mod = __import__(module)
  File "/usr/share/weewx/user/GTS.py", line 2
**SyntaxError: Non-ASCII character '\xc3' in file /usr/share/weewx/user/GTS.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details**

**Comment by kobi80** [comment]
habe in der GTS.py die Umlaute umbenannt > ue
Leider kommt es nun zum nächsten Fehler beim erstellen der Reports.

Using configuration file /etc/weewx/weewx.conf
Traceback (most recent call last):
  File "/usr/share/weewx/wee_reports", line 103, in <module>
    main()
  File "/usr/share/weewx/wee_reports", line 69, in main
    engine = weewx.engine.DummyEngine(config_dict)
  File "/usr/share/weewx/weewx/engine.py", line 93, in __init__
    self.loadServices(config_dict)
  File "/usr/share/weewx/weewx/engine.py", line 161, in loadServices
    obj = weeutil.weeutil.get_object(svc)(self, config_dict)
  File "/usr/share/weewx/user/GTS.py", line 630, in __init__
    self.GTSextension=GTSType(__lat,__lon)
  File "/usr/share/weewx/user/GTS.py", line 192, in __init__
    self.lmt_tz=datetime.timezone(self.timeoffset,"LMT")
**AttributeError: 'module' object has no attribute 'timezone'**

**Comment by roe-dl** [comment]
manuell Installation:

Datei GTS.py nach /usr/share/weewx/user/.

In /etc/weewx/weewx.conf:
Abschnitt \[Engine\]
Unterabschnitt \[\[Services\]\]
In Eintrag xtype_services anfügen `user.GTS.GTSService`

**Comment by roe-dl** [comment]
Laut Python-Dokumentation gibt es "timezone" im Modul "datetime", und bei mir beanstandet es die Zeile auch nicht. Sie ist auch wichtig für die Funktion.

Kann es sein, daß das Modul "datetime" nicht in der aktuellen Version vorliegt?

[timezone in Python-Doc](https://docs.python.org/3/library/datetime.html?highlight=datetime#datetime.timezone)

**Comment by roe-dl** [comment]
Ich habe noch etwas das Internet durchstöbert, und es gibt dort einige Kommentare, die nahelegen, daß das datetime-Modul von Python 2 keine Klasse datetime.timezone hat, während die Version für Python 3 darüber verfügt. Im Moment weiß ich nicht, wie ich das lösen soll, außer den Umstieg auf Python 3 zu empfehlen.

**Comment by kobi80** [comment]
also WEEWX nutzt bei mir Pyhton 2.7.16
Ich habe aber auch Pyhton 3 installiert.
Hm. wie kann ich WEEWX nun sagen, dass es die 3er Version nutzen soll?


![image](https://user-images.githubusercontent.com/79660810/109269032-350e4380-780c-11eb-8ef8-7538202cf21a.png)

**Comment by kobi80** [comment]
Update von Phyton 2 auf 3 
http://weewx.com/docs/debian.htm

ich habe einfach diese Befehle ausgeführt und schon wird die 3er Version genutzt. Bestehende Config wir beibehalten

wget -qO - https://weewx.com/apt/weewx-python3.list | sudo tee /etc/apt/sources.list.d/weewx.list
sudo apt-get update
sudo apt-get install weewx
