### ISSUE TITLE
MySQL error in "calc_derived" function

### ISSUE THREAD

**Issue by Jterrettaz** [roe-dl/weewx-GTS#15]
hello,
I had MYSQL error in the function calc_derived each time I used an aggregate interval.
After some investigation, it appeared that at least on my system running  Python 3.7.3 (Raspberry Pi) I needed to reformat the MySQL query to avoid any error : 
` for _result in db_manager.genSql(
                    "SELECT `dateTime`,`usUnits`,`outTemp`,`outHumidity`,`pressure` from %s WHERE dateTime> %d AND dateTime<= %d ORDER BY `dateTime`" % (db_manager.table_name,timespan.start,timespan.stop)):`

**Comment by roe-dl** [comment]
Could you provide the exact error message?

**Comment by Jterrettaz** [comment]
Here is a log with an aggregate interval  and aggregate type configured for both the "Seasons" and "Belchertown" skin. The exact line numbers indicated may not correspond to your original GTS.py since I added some loginf() lines to understand what was happening. Anyway, the line number corresponds to the SQL Query in the calc_derived function. 
 
2022-08-22 22:00:25  weewx[15344] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 4.19 seconds
2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****  (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY `dateTime`' at line 1")
2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****  Traceback (most recent call last):

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weedb/mysql.py", line 54, in guarded_fn

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      return fn(*args, **kwargs)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weedb/mysql.py", line 266, in execute

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      self.cursor.execute(mysql_string, tuple(sql_tuple))

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 250, in execute

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      self.errorhandler(self, exc, value)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      raise errorvalue

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 247, in execute

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      res = self._query(query)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 411, in _query

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      rowcount = self._do_query(q)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 374, in _do_query

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      db.query(q)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 292, in query

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      _mysql.connection.query(self, query)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****  _mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY `dateTime`' at line 1")

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****  

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****  

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****  Traceback (most recent call last):

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      obj.start()

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 385, in start

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      self.run()

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 42, in run

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      self.gen_images(self.gen_ts)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 109, in gen_images

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      self.image_dict[timespan][plotname])

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 249, in gen_plot

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      **option_dict)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 101, in get_series

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      aggregate_interval, **option_dict)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 167, in get_series

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      agg_vt = get_aggregate(obs_type, stamp, do_aggregate, db_manager)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 128, in get_aggregate

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      **option_dict)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 1039, in get_aggregate

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      return self.calc_derived(obs_type,timespan,aggregate_type,db_manager)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 885, in calc_derived

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      % db_manager.table_name,timespan):

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/manager.py", line 473, in genSql

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      for _row in _cursor.execute(sql, sqlargs):

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weedb/mysql.py", line 63, in guarded_fn

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****      raise klass(e)

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****  weedb.DatabaseError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY `dateTime`' at line 1")

2022-08-22 22:00:40  weewx[15344] ERROR weewx.reportengine:         ****  Generator terminated
2022-08-22 22:00:40  weewx[15344] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx
2022-08-22 22:00:44  weewx[15344] INFO weewx.cheetahgenerator: Generated 3 files for report tagssciez in 4.62 seconds
2022-08-22 22:00:44  weewx[15344] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/tagssciez
2022-08-22 22:00:45  weewx[15344] INFO weewx.cheetahgenerator: Generated 1 files for report xstats in 0.80 seconds
2022-08-22 22:00:52  weewx[15344] INFO weewx.cheetahgenerator: Generated 11 files for report Belchertown in 7.05 seconds
2022-08-22 22:00:52  weewx[15344] INFO weewx.reportengine: Copied 2 files to /var/www/html/weewx/belchertown
2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.belchertown.HighchartsJsonGenerator'
2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  Error trying to use database binding wx_binding to graph observation outHumAbs. Error was: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY `dateTime`' at line 1").
2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  Traceback (most recent call last):

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weedb/mysql.py", line 54, in guarded_fn

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      return fn(*args, **kwargs)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weedb/mysql.py", line 266, in execute

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      self.cursor.execute(mysql_string, tuple(sql_tuple))

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 250, in execute

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      self.errorhandler(self, exc, value)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      raise errorvalue

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 247, in execute

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      res = self._query(query)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 411, in _query

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      rowcount = self._do_query(q)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 374, in _do_query

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      db.query(q)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 292, in query

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      _mysql.connection.query(self, query)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  _mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY `dateTime`' at line 1")

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  Traceback (most recent call last):

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 2353, in get_observation_data

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      (time_start_vt, time_stop_vt, obs_vt) = archive.getSqlVectors(TimeSpan(start_ts, end_ts), obs_lookup, aggregate_type, aggregate_interval)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/manager.py", line 488, in getSqlVectors

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      aggregate_type, aggregate_interval)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 101, in get_series

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      aggregate_interval, **option_dict)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 167, in get_series

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      agg_vt = get_aggregate(obs_type, stamp, do_aggregate, db_manager)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 128, in get_aggregate

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      **option_dict)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 1039, in get_aggregate

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      return self.calc_derived(obs_type,timespan,aggregate_type,db_manager)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 885, in calc_derived

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      % db_manager.table_name,timespan):

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/manager.py", line 473, in genSql

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      for _row in _cursor.execute(sql, sqlargs):

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weedb/mysql.py", line 63, in guarded_fn

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      raise klass(e)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  weedb.DatabaseError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY `dateTime`' at line 1")

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  Traceback (most recent call last):

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      obj.start()

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 385, in start

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      self.run()

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1841, in run

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      series_data = self.get_observation_data(binding, archive, observation_type, minstamp, maxstamp, aggregate_type, aggregate_interval, time_length, xAxis_groupby, xAxis_categories, mirrored_value, weatherRange_obs_lookup, wind_rose_color)

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 2355, in get_observation_data

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****      raise Warning( "Error trying to use database binding %s to graph observation %s. Error was: %s." % (binding, obs_lookup, e) )

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  Warning: Error trying to use database binding wx_binding to graph observation outHumAbs. Error was: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY `dateTime`' at line 1").

2022-08-22 22:01:04  weewx[15344] ERROR weewx.reportengine:         ****  Generator terminated

**Comment by roe-dl** [comment]
[genSql() error with MySQL](https://groups.google.com/g/weewx-development/c/aJS_kpoJ31U)

**Comment by Jterrettaz** [comment]
No more errors when the space is added before `ORDER`

**Comment by roe-dl** [comment]
fixed
