### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by belidi** [roe-dl/weewx-GTS#4]
Hello, I have a problem installing your application:

sudo wee_extension --install weewx-GTS.zip 
Request to install 'weewx-GTS.zip'
Extracting from zip archive weewx-GTS.zip
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 125, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 147, in install_from_dir
    extension_dir)
  File "/usr/share/weewx/weecfg/__init__.py", line 1866, in get_extension_installer
    __import__('install')
  File "/var/tmp/weewx-GTS-master/install.py", line 21
    'Calculations'{
                  ^
SyntaxError: invalid syntax

Weewx .4.4.0   (/etc/weewx/... )

**Comment by roe-dl** [comment]
I found the reason. Please download the extension again and try it again.

**Comment by belidi** [comment]
ok, it works

**Comment by roe-dl** [comment]
Thank you for trying GTS.
