### ISSUE TITLE
Unrecoverable exception after install

### ISSUE THREAD

**Issue by rodolfozan** [roe-dl/weewx-GTS#7]
Hello,

i get the following error when trying to restart weewx after install of your GTS extension:

`May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__: Caught unrecoverable exception:
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****  offset must be a timedelta representing a whole number of minutes, not datetime.timedelta(0, 2445, 168000).
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****  Traceback (most recent call last):
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 151, in main
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 93, in __init__
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****      self.loadServices(config_dict)
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 161, in loadServices
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****    File "/usr/share/weewx/user/GTS.py", line 765, in __init__
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****      self.GTSextension=GTSType(__lat,__lon)
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****    File "/usr/share/weewx/user/GTS.py", line 209, in __init__
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****      self.lmt_tz=datetime.timezone(self.timeoffset,"LMT")
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****  ValueError: offset must be a timedelta representing a whole number of minutes, not datetime.timedelta(0, 2445, 168000).
May 20 11:24:29 raspberrypi weewx[29526] CRITICAL __main__:     ****  Exiting.
`

**Comment by roe-dl** [comment]
Could you say, which version of Python you use? This error typically occurs for Python version before 3.7.

**Comment by roe-dl** [comment]
I made some changes. Please, download the extension and install it again and try. Be aware that this is a work-around for Python versions that do not allow timezone offset to be seconds.

**Comment by rodolfozan** [comment]
Thanks for the quick reply. 
Unfortunetly it doesnt work - the following exception is thrown:

May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__: Caught unrecoverable exception:
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  module 'datetime' has no attribute 'timdedelta'
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  Traceback (most recent call last):
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/user/GTS.py", line 210, in __init__
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      self.lmt_tz=datetime.timezone(self.timeoffset,"LMT")
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  ValueError: offset must be a timedelta representing a whole number of minutes, not datetime.timedelta(0, 2445, 168000).
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  Traceback (most recent call last):
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 151, in main
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 93, in __init__
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      self.loadServices(config_dict)
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 161, in loadServices
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/user/GTS.py", line 771, in __init__
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      self.GTSextension=GTSType(__lat,__lon)
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/user/GTS.py", line 214, in __init__
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      self.timeoffset = datetime.timdedelta(minutes=(lon*240)//60)
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  AttributeError: module 'datetime' has no attribute 'timdedelta'
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  Exiting.
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__: Caught unrecoverable exception:
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  module 'datetime' has no attribute 'timdedelta'
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  Traceback (most recent call last):
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/user/GTS.py", line 210, in __init__
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      self.lmt_tz=datetime.timezone(self.timeoffset,"LMT")
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  ValueError: offset must be a timedelta representing a whole number of minutes, not datetime.timedelta(0, 2445, 168000).
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****  Traceback (most recent call last):
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 151, in main
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 93, in __init__
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      self.loadServices(config_dict)
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 161, in loadServices
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****    File "/usr/share/weewx/user/GTS.py", line 771, in __init__
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:     ****      self.GTSextension=GTSType(__lat,__lon)
May 20 12:53:46 raspberrypi weewx[11109] CRITICAL __main__:  May 20 12:56:40 raspberrypi systemd[1]: Stopping LSB: weewx weather system...

**Comment by c0by85** [comment]
Please check your python version. i got no problems with this addon.

```
root@weather  ~ python3 --version
Python 3.9.4
```

**Comment by roe-dl** [comment]
Oh. I found a typo. Sorry. Please, try again.

**Comment by rodolfozan** [comment]
Now it is working - thanks again.
